version: "3.8"

services:
  backend:
    image: example-backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: example-backend
    depends_on:
      - db

  frontend:
    image: example-frontend
    ports:
      - "5000:5000"
    container_name: example-frontend

  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
