version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REQUEST_ORIGIN=http://localhost/
    container_name: example-backend
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_API_URL=http://localhost/api/
    container_name: example-frontend

  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
